# Generated by Django 2.2.6 on 2019-10-06 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=255)),
                ('order_description', models.CharField(max_length=255)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_amount', models.PositiveSmallIntegerField(default=1)),
                ('order_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
